//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace layOut20192.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public client()
        {
            this.reservation_car = new HashSet<reservation_car>();
        }
    
        public string ssna { get; set; }
        public string name { get; set; }
        public int t_ID { get; set; }
        public int ID { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<int> number_of_reservation { get; set; }
        public Nullable<int> age { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    
        public virtual type_client type_client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservation_car> reservation_car { get; set; }
    }
}
