//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace layOut20192.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation_car
    {
        public int car_ID { get; set; }
        public System.DateTime start_Date { get; set; }
        public System.DateTime end_date { get; set; }
        public int number { get; set; }
        public string client_ID { get; set; }
        public string type_reservation { get; set; }
        public Nullable<bool> package { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> package_ID { get; set; }
    
        public virtual car car { get; set; }
        public virtual client client { get; set; }
        public virtual package package1 { get; set; }
    }
}
