//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newAgency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class setting_agency
    {
        public string ssna { get; set; }
        public string Name { get; set; }
        public string admin_Name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    }
}
